// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdV7pVS7ONSxP4496XtyCpOO0AP-3PqN4',
    appId: '1:723271484580:android:070f1a92a28c7931c7d231',
    messagingSenderId: '723271484580',
    projectId: 'adoptapp-b99f5',
    databaseURL: 'https://adoptapp-b99f5-default-rtdb.firebaseio.com',
    storageBucket: 'adoptapp-b99f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-_dCf885QP23CCAsvLrACfBFXkkBTuY',
    appId: '1:723271484580:ios:88027aa4ef1441a7c7d231',
    messagingSenderId: '723271484580',
    projectId: 'adoptapp-b99f5',
    databaseURL: 'https://adoptapp-b99f5-default-rtdb.firebaseio.com',
    storageBucket: 'adoptapp-b99f5.appspot.com',
    iosClientId:
        '723271484580-l25a9bo8gh9ck14qdl2u2f4kd606a3fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptapp',
  );
}
